name: build and deploy app

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: fnwicr.azurecr.io

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build container
        run: |
          docker build -t "${{ env.REGISTRY }}/canvasimport:latest" .
          docker push "${{ env.REGISTRY }}/canvasimport:latest"

  release:
    runs-on: self-hosted
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build chart and release
        env:
          UPDATER_SECRET: ${{ secrets.UPDATER_SECRET_K8S }}
        run: |
          set -euxo pipefail
          export VERSION=$(date "+0.1.%Y%m%d%H%M%S")
          helm package --version "${VERSION}" --app-version "${VERSION}" charts/canvasimport
          helm push "canvasimport-${VERSION}.tgz" oci://${{ env.REGISTRY }}/helm
          
          curl "https://k8s.datanose.nl/gitops-updater?name=canvastools&secret=${UPDATER_SECRET}&version=${VERSION}"